### ISSUE TITLE
no found pysif.py

### ISSUE THREAD

**Issue by wt76cn** [hujc91/pysif#1]
C:\Python37\python.exe D:/PyPostPiv/pysif-master/validation/taylor-green-512/taylor-green-512-run.py
Traceback (most recent call last):
  File "D:/PyPostPiv/pysif-master/validation/taylor-green-512/taylor-green-512-run.py", line 8, in <module>
    tg_solver.solve()
AttributeError: 'solver' object has no attribute 'solve'

**Comment by wt76cn** [comment]
C:\Python37\python.exe D:/PyPostPiv/pysif-master/validation/taylor-green-512/taylor-green-512-run.py
Traceback (most recent call last):
  File "D:/PyPostPiv/pysif-master/validation/taylor-green-512/taylor-green-512-run.py", line 8, in <module>
    tg_solver.solve()
AttributeError: 'solver' object has no attribute 'solve'
